name: 'Zekt Event Action'
description: 'Send workflow events to Zekt broker for distribution to consumers. No secrets required - uses GitHub OIDC for authentication.'
author: 'zekt-dev-org'

branding:
  icon: 'send'
  color: 'orange'

inputs:
  event-type:
    description: 'The type of event to send (e.g., deployment, release, build-complete)'
    required: true
  payload:
    description: 'JSON payload to send with the event'
    required: false
    default: '{}'
  zekt-api-url:
    description: 'Zekt API URL (optional - defaults to production)'
    required: false
    default: 'https://zekt-customer-api.azurewebsites.net'

outputs:
  event-id:
    description: 'The unique ID of the sent event'
    value: ${{ steps.send-event.outputs.event_id }}
  status:
    description: 'Status of the event submission (success/failed)'
    value: ${{ steps.send-event.outputs.status }}
  consumers-notified:
    description: 'Number of consumers that will receive this event'
    value: ${{ steps.send-event.outputs.consumers_notified }}

runs:
  using: 'composite'
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.event-type }}" ]; then
          echo "::error::event-type is required"
          exit 1
        fi
        
        # Validate payload is valid JSON
        if ! echo '${{ inputs.payload }}' | jq . > /dev/null 2>&1; then
          echo "::error::payload must be valid JSON"
          exit 1
        fi
        
        echo "âœ… Inputs validated"

    - name: Get OIDC Token
      id: get-token
      shell: bash
      run: |
        echo "ðŸ” Requesting OIDC token from GitHub..."
        
        # Check if OIDC is available
        if [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] || [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
          echo "::error::OIDC token request not available. Ensure the workflow has 'permissions: id-token: write'"
          exit 1
        fi
        
        # Request OIDC token with Zekt audience
        OIDC_RESPONSE=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://zekt")
        
        OIDC_TOKEN=$(echo "$OIDC_RESPONSE" | jq -r '.value')
        
        if [ -z "$OIDC_TOKEN" ] || [ "$OIDC_TOKEN" == "null" ]; then
          echo "::error::Failed to obtain OIDC token"
          echo "Response: $OIDC_RESPONSE"
          exit 1
        fi
        
        # Mask the token in logs
        echo "::add-mask::$OIDC_TOKEN"
        echo "oidc_token=$OIDC_TOKEN" >> $GITHUB_OUTPUT
        
        echo "âœ… OIDC token obtained successfully"

    - name: Send Event to Zekt
      id: send-event
      shell: bash
      env:
        ZEKT_API_URL: ${{ inputs.zekt-api-url }}
        EVENT_TYPE: ${{ inputs.event-type }}
        PAYLOAD: ${{ inputs.payload }}
        OIDC_TOKEN: ${{ steps.get-token.outputs.oidc_token }}
      run: |
        echo "ðŸ“¤ Sending event to Zekt..."
        echo "   API URL: $ZEKT_API_URL"
        echo "   Event Type: $EVENT_TYPE"
        echo "   Repository: $GITHUB_REPOSITORY"
        
        # Build the request body
        REQUEST_BODY=$(jq -n \
          --arg eventType "$EVENT_TYPE" \
          --arg repository "$GITHUB_REPOSITORY" \
          --arg runId "$GITHUB_RUN_ID" \
          --arg actor "$GITHUB_ACTOR" \
          --arg sha "$GITHUB_SHA" \
          --arg ref "$GITHUB_REF" \
          --arg workflow "$GITHUB_WORKFLOW" \
          --argjson payload "$PAYLOAD" \
          '{
            eventType: $eventType,
            repository: $repository,
            workflowRunId: $runId,
            triggeredBy: $actor,
            commitSha: $sha,
            ref: $ref,
            workflow: $workflow,
            payload: $payload,
            timestamp: (now | todate)
          }')
        
        # Send to Zekt API with OIDC token
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          "$ZEKT_API_URL/api/events/receive" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OIDC_TOKEN" \
          -H "X-GitHub-Repository: $GITHUB_REPOSITORY" \
          -d "$REQUEST_BODY")
        
        # Extract status code (last line) and body (everything else)
        HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
        RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')
        
        echo "   HTTP Status: $HTTP_CODE"
        
        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          echo "âœ… Event sent successfully!"
          
          # Parse response
          EVENT_ID=$(echo "$RESPONSE_BODY" | jq -r '.eventId // "unknown"')
          CONSUMERS=$(echo "$RESPONSE_BODY" | jq -r '.consumersNotified // 0')
          MESSAGE=$(echo "$RESPONSE_BODY" | jq -r '.message // "Event received"')
          
          echo "event_id=$EVENT_ID" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT
          echo "consumers_notified=$CONSUMERS" >> $GITHUB_OUTPUT
          
          echo ""
          echo "ðŸ“‹ Event Details:"
          echo "   Event ID: $EVENT_ID"
          echo "   Consumers Notified: $CONSUMERS"
          echo "   Message: $MESSAGE"
        else
          echo "::error::Failed to send event to Zekt (HTTP $HTTP_CODE)"
          echo "Response: $RESPONSE_BODY"
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "event_id=" >> $GITHUB_OUTPUT
          echo "consumers_notified=0" >> $GITHUB_OUTPUT
          exit 1
        fi

    - name: Write Job Summary
      shell: bash
      if: always()
      run: |
        echo "### ðŸ“¨ Zekt Event Delivery" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Event Type | \`${{ inputs.event-type }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Repository | \`${{ github.repository }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Workflow | \`${{ github.workflow }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Run ID | \`${{ github.run_id }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Status | **${{ steps.send-event.outputs.status || 'unknown' }}** |" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.send-event.outputs.status }}" == "success" ]; then
          echo "| Event ID | \`${{ steps.send-event.outputs.event_id }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Consumers Notified | ${{ steps.send-event.outputs.consumers_notified }} |" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "_Sent via [Zekt Action](https://github.com/zekt-dev-org/zekt-action)_" >> $GITHUB_STEP_SUMMARY
