name: 'Zekt Event Publisher'
description: 'Send custom event payloads to Zekt orchestration platform'
author: 'zekt-dev-org'

branding:
  icon: 'send'
  color: 'blue'

inputs:
  zekt_run_id:
    description: 'GitHub workflow run ID'
    required: true

  zekt_step_id:
    description: 'Unique step identifier for multiple actions in same workflow'
    required: false
    default: 'default-step'

  zekt_payload:
    description: 'Custom JSON payload to send to consumers (max 512 KB)'
    required: true

  github_token:
    description: 'GitHub token for authentication'
    required: true

outputs:
  success:
    description: 'Whether the payload was successfully registered (true/false)'

  run_id:
    description: 'The workflow run ID that was registered'

  step_id:
    description: 'The step ID that was registered'

  error_message:
    description: 'Error message if registration failed (empty on success)'

runs:
  using: 'node20'
  main: 'dist/index.js'
